### PR TITLE
Add CLI for download function

### PR DESCRIPTION
**Pull request by andrey-hohlov**
Hi! Thanks for great module.

I think it's nice ability to start new project by downloading template from repository.

Like a:

```bash
mkdir new-project
cd new-project
download-git-repo user/repo
```

### CODE REVIEW

**Comment by flipxfx** [comment]
While I think this is a great idea I would rather the cli be a separate repo like `download-git-repo-cli`. Similar to the way [download](https://github.com/kevva/download)/[download-cli](https://github.com/kevva/download-cli) does it. I don't want to add unnecessary code to this repo. In the separate repo we could be a little more robust (adding help etc.). We could prefer that the cli repo be installed globally. It'd be nice to have the cli behave like:

```
download-git-repo user/repo path/new-project
```

What you think?

**Comment by andrey-hohlov** [comment]
I want this tool ASAP)

First I created separate module like you say - `download-git-repo-cli`

But I thought that maybe you would want to do this module and be maintainer of both, or you want add this functionality to `download-git-repo`...

And maked this PR.

It's ready to global install, and supports path to download and -c (--clone) option:

```download-git-repo user/repo path/new-project --clone```

So, if you want - you can create separate repo, or i can create it.
Just say what you decided and lets do it

**Comment by flipxfx** [comment]
Yeah I guess it makes sense for me to take ownership of it. If you want it ASAP I can't do any development right now, but if you submit the pull request I can merge it with my iPhone app. I made the repo.

**Comment by andrey-hohlov** [comment]
For now I will use the local version and and waiting until you publish it on npm.

**Comment by flipxfx** [comment]
Ok just do the pull request when you can and I'll merge and publish after.

**Comment by andrey-hohlov** [comment]
@flipxfx tomorrow i will do this.

And I confused - how to make PR to empty repo that i can't clone?

**Comment by flipxfx** [comment]
Oops try now.

**Pull request closed without merging**
