### PR TITLE
Add ssh option

### PR DESCRIPTION
**Pull request by egermano**
Use https as default but add a ssh in options for clone options

### CODE REVIEW

**Comment by flipxfx** [comment]
I would like to default to SSH. This introduces a breaking change. I'd rather default to the current way it's working using SSH and if a protocol is present then use it instead. Then you could wrap the `addProtocol` function further to handle this. Something like: 

```js
function addProtocol (origin, clone) {
  if (!/^(f|ht)tps?:\/\//i.test(origin)) {
    if (clone)
      origin = "git@" + origin
    else
      origin = "https://" + origin
  }

  // Add trailing slash or colon (for ssh)
  if (/^git\@/i.test(origin)) {
    origin = origin + ":"
  else
    origin = origin + "/"

  return url
}
```

Then the specific url generators would look like
```js
function bitbucket (repo, clone) {
  var url

  if (clone)
    url = addProtocol(repo.origin, clone) + repo.owner + "/" + repo.name + ".git"
  else
    url = addProtocol(repo.origin, clone) + repo.owner + "/" + repo.name + "/get/" + repo.checkout + ".zip"

  return url
}
```

I wrote this real quick without testing but I think it would work.

**Comment by egermano** [comment]
I moved the ssh conditional to addProtocol and make these option `true` by default as you suggested.

Discard the README changes.

**Comment by egermano** [comment]
I've changed how the ssh option is set by default

**Comment by flipxfx** [comment]
I still think this can be done without an separate option for it. I'll try and implement it.

**Comment by flipxfx** [comment]
I went ahead and added the ability to add custom origins for git clone with default `git@` protocol.
So in your case if you want to use https for a clone rather than default ssh you would do use something like
```javascript
download('https://github.com:flipxfx/download-git-repo-fixture#my-branch', 'test/tmp', function (err) {
  console.log(err ? "Error" : "Success")
})
```

**Comment by egermano** [comment]
Thank you!:)

**Pull request closed without merging**
