### PR TITLE
Add direct url

### PR DESCRIPTION
**Pull request by flipxfx**
To handle #19, add the ability to hit a url directly.

### CODE REVIEW

**Comment by flipxfx** [comment]
@kuangcaibao Can you try this? Let me know if it makes sense and works for you.

**Comment by tweet** [comment]
Hi, I've tried this direct branch, it works well for my local work env, please merge this to master, thanks.

**Comment by beatgrabe** [comment]
Hey,

I am using the `vue/cli` which is using your [package](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/util/loadRemotePreset.js#L7) to clone app presets from git repos. I  think it would be a huge benefit for the vue community to be able to clone from non `github`/`gitlab`/`bitbucket` repos. So I would really appriciate a merge ;-)

**Comment by flipxfx** [comment]
Ok. I had some feedback about a different way to do it but never got a response. So I'll work on getting this merged soon 👍

**Pull request merged**
