### PR TITLE
Remove existing dir

### PR DESCRIPTION
**Pull request by egoist**
Fix https://github.com/vuejs/vue-cli/issues/355#issuecomment-280553052

### CODE REVIEW

**Comment by flipxfx** [comment]
The line you removed was to clean up the `.git` folder after successfully downloading the folder. The line you added doesn't make since as it would remove the folder you just downloaded.

**Comment by egoist** [comment]
Right, we should add `rm(dest)` before `gitclone` then?

**Comment by egoist** [comment]
Fixed, what do you think now?

**Comment by flipxfx** [comment]
Sorry, I'm kinda nervous about this. I feel like this should be part of vue-cli and not this project. If someone accidentally puts the wrong path they could, without warning, delete an entire folder of stuff. The only thing this repo deletes is the leftover `.git` folder after a gitclone so the user is left with just the project files.

I feel like this issue would be better resolved in vue-cli itself, as it knows it will just be deleting a temporary file. We could maybe add a force remove destination flag to this repo but it would require an update to vue-cli anyway.

**Comment by flipxfx** [comment]
Looks like it's being taken care of in the vue-cli. Closing.

**Pull request closed without merging**
